from proof import ProofContext
from tarski import axioms, Congruent, Equal, Between
from formula import (UniversalQuantifier as ForAll,
                     ExistentialQuantifier as Exists)

p = ProofContext(axioms)
x,y = p.start_context(2)
F1 = p.specialise(axioms[1], (y,x,x,y,x,y))
F2 = p.specialise(axioms[0], (y,x))
p.conjunction(F2, F2)
F3 = p.modus_ponens(F1)
Thm_2_1 = p.directproof(F3)
assert Thm_2_1 == ForAll((1,2), Congruent(1,2,1,2))

x,y,r,s = p.start_context(4)
F3 = p.assume(Congruent(x,y,r,s))
F4 = p.specialise(Thm_2_1, (x,y))
F5 = p.specialise(axioms[1], (x,y,r,s,x,y))
F6 = p.conjunction(F3, F4)
F7 = p.modus_ponens(F5)
Thm_2_2 = p.directproof(Congruent(r,s,x,y))
assert Thm_2_2 == ForAll((1,2,3,4), Congruent(1,2,3,4) > Congruent(3,4,1,2))

a,b,c,d,e,f = p.start_context(6)
H1 = p.assume(Congruent(a,b,c,d))
H2 = p.assume(Congruent(c,d,e,f))
H3 = p.specialise(Thm_2_2,(a,b,c,d))
H4 = p.modus_ponens(H3)
p.conjunction(H4,H2)
H5 = p.specialise(axioms[1], (c,d,a,b,e,f))
H6 = p.modus_ponens(H5)
Thm_2_3 = p.directproof(H6)
assert Thm_2_3 == ForAll((1,2,3,4,5,6), Congruent(1,2,3,4) & Congruent(3,4,5,6) > Congruent(1,2,5,6))

a,b,c,d = p.start_context(4)
X0 = p.assume(Congruent(a,b,c,d))
X1 = p.specialise(axioms[0], (b,a))
X2 = p.specialise(Thm_2_3, (b,a,a,b,c,d))
p.conjunction(X1, X0)
X3 = p.modus_ponens(X2)
Thm_2_4 = p.directproof(X3)
assert Thm_2_4 == ForAll((1,2,3,4), Congruent(1,2,3,4)>Congruent(2,1,3,4))
